fragment HeroParts on Hero {
  __typename
  badgeText
  mainHeading
  subtext
  backgroundImage
  videoUrl
}

fragment TvShowParts on TvShow {
  __typename
  title
  description
  image
  airDate
  videoUrl
  category
  orderRank
}

fragment EventParts on Event {
  __typename
  title
  date
  venue
  time
  price
  type
  shortDescription
  coverImage
  bookingUrl
  orderRank
}
